### ISSUE TITLE
Encouter "Insufficient memory" issue when try to extract サノバウィッチ

### ISSUE THREAD

**Issue by lordfriend** [xmoeproject/KrkrExtract#10]
The game is newly installed, I drag the game into krkrExtract.exe, the game started without problem and the krkrExtract window opened as well. But when I dragged the xp3 file into the extracter window. It said "Insufficient memory" and then nothing happened.

![capture](https://cloud.githubusercontent.com/assets/1235614/17837531/480eb61a-67e8-11e6-887e-046b8caaacad.PNG)

My system is Windows 8.1 pro English, non-unicode page has been set to Japanese.

CPU: Xeon E3-1230,
Memory: 16G

**Comment by xmoeproject** [comment]
sorry for replying so late.
now, version 1.0.3.1 solved this problem.
plz update your tool.

**Comment by lordfriend** [comment]
Thank you very much to fix this issue!
