### ISSUE TITLE
about applications from steam

### ISSUE THREAD

**Issue by gloomy-lyre** [xmoeproject/KrkrExtract#104]
Could this be used in extracting galgames downloaded from steam ?
I've tried once but there is only game that runs normally,and the windows of krkrextract didn't show up
I wonder if i've not follow the right steps or this just couldn't extract it
the contents in the game folder are .xp3 .exe .sig .cf So I think it's kirikiri type

**Comment by marcussacana** [comment]
Steam is a DRM, and a DRM don't want you injecting things in their game.
Crack the steam stub first, after that the tool should work.

**Comment by gloomy-lyre** [comment]
though I try use steamless to removed drm, steam API 's layer of drm won't be removed, so they can't cooperate. 
so I try the loader and I can drag the loader to this application and the game normally open but ,this extractor's window won't show up.
Seems this application doesn't support smart steam loader, sadly

**Comment by marcussacana** [comment]
Even if you use only the steamless the steam api still call the steam, you must use the steamless to patch the stub and use a emulator of the steam api.

**Comment by gloomy-lyre** [comment]
@marcussacana following your saying I've succeed in running and unpacking it.Thanks a lot.

**Comment by xmoeproject** [comment]
just use the none-steam version (or DRM-free version).
supporting various DRMs is a hard task and may have compatibility issues
![image](https://user-images.githubusercontent.com/10909416/102837959-fe950080-4437-11eb-8ff4-6db4ca85bead.png)
