### ISSUE TITLE
Universal Patcher not working on 9-nine- 普通版/豪華版 .exe file

### ISSUE THREAD

**Issue by neump** [xmoeproject/KrkrExtract#110]
Even after converting/patching the .exe file, it sill asks for the product key, I tried it with a different game (9-nine-そらいろ) and it worked. Probably, ぱれっと implemented some kind of detection of some sort, I don't know. I looked into a decompiler/disassembler but as a novice, I can't make any sense of it.

Screenshots:

![Screenshot (857)](https://user-images.githubusercontent.com/83550781/116822563-7b8c6f80-abba-11eb-80ab-6bc3b700c595.png)

![Screenshot (858)](https://user-images.githubusercontent.com/83550781/116822572-81825080-abba-11eb-8421-8916a9515f0a.png)

**Comment by jszhtian** [comment]
![image](https://user-images.githubusercontent.com/23244094/118407776-7f23fa00-b682-11eb-9725-9d23ee63236f.png)
Just comment the cdkey check part in default.tjs file.

**Comment by neump** [comment]
I'm sorry but what is a default.tjs file?

**Comment by jszhtian** [comment]
> I'm sorry but what is a default.tjs file?

use krkrextract unpack the data.xp3. then use universal patch to load modified default.tjs

**Comment by neump** [comment]
I've found it. Then, I have to repack it again right?

**Comment by neump** [comment]
Thank you very much. Your explanation is really easy to follow.  Also, I'm really sorry if I looked like an idiot. I should've tested and experimented more to explore other ways to fix it. I should've cross referenced it to the other one that worked. After looking at it now, it was pretty obvious. I hope you have a nice day!
