### ISSUE TITLE
Packing problems

### ISSUE THREAD

**Issue by scese250** [xmoeproject/KrkrExtract#12]
Trying to packing a folder with subfolders, but the program just don't detect these folders. 
I'm working with Karakara. If I'm doing something wrong, tell me.

https://vgy.me/SV2Gcu.png

**Comment by marcussacana** [comment]
repack as patch.xp3, put all files in the same directory

**Comment by scese250** [comment]
Thanks, it worked.

**Comment by xmoeproject** [comment]
Why : subfolders are not in auto search areas
