### ISSUE TITLE
How to launch a game that needs LocaleEmulator with KrkrExtract?

### ISSUE THREAD

**Issue by ShamanKai** [xmoeproject/KrkrExtract#123]
If I drop the executable in KrkrExtract, I launch the game without LocaleEmulator so how to do

**Comment by marcussacana** [comment]
change your system locale instead., it's possible use krkrextract + LE, but any locale emulator is hacky, Just change the system locale.

**Comment by ShamanKai** [comment]
> change your system locale instead., it's possible use krkrextract + LE, but any locale emulator is hacky, Just change the system locale.
My system's regional settings are JAP but my game won't start. LocaleEmulator is the only way to launch it that I found.
I just tested with another game and KrkrExtract closes instantly on opening

**Comment by marcussacana** [comment]
Then you changed the wrong settings, it's very commom the people think that system locale = system region,
anyway it's in this part that you need change, also, check/uncheck the UTF-8 in that same window, can help solve problems as well
![image](https://user-images.githubusercontent.com/10576957/141369379-d3840b5a-dde4-4a1c-93a8-88f80b0265b5.png)

**Comment by ShamanKai** [comment]
Wow, it works. I must have made a mistake but now I find myself in the same situation as many of the searches I've done. The KrkrExtract software doesn't launch in any way.
Thanks for the help
