### ISSUE TITLE
Trojan detected

### ISSUE THREAD

**Issue by Maxy7171** [xmoeproject/KrkrExtract#126]
Window defender detected Trojan:Win32/Wacatac.B!ml. I also tried to extract the XP3 file but failed due to the Trojan.

**Comment by xmoeproject** [comment]
1. KrkrExtract requires in-memory tempering technique, which is considered malicious by the most antivirus softwares.
2. Since this is an open source project, you can build by yourself rather than downloading from release page or even some untrusted locations.
