### ISSUE TITLE
最新版对某些游戏无法解包

### ISSUE THREAD

**Issue by 1119553797** [xmoeproject/KrkrExtract#15]
![qq 20161113191403](https://cloud.githubusercontent.com/assets/6320806/20245132/60d1b682-a9d5-11e6-8c33-f965f7eef0e8.png)
回退到SenrenBanka之前的版本正常使用

**Comment by 1119553797** [comment]
回退到对千恋支持之前的版本出现以下的提示
![qq 20161113202318](https://cloud.githubusercontent.com/assets/6320806/20245593/70d43fd2-a9df-11e6-9eef-7eab87f7dbe5.png)
另外在最新版本夏空彼方也是出现一楼的图，换成旧版本正常使用

**Comment by xmoeproject** [comment]
Ok, KrkrkExtract now works with "DRACU-RIOT!".


"还有希望psd解出来的能是png而不是bmp"
这个功能考虑在下一版本推出。
