### ISSUE TITLE
请教一下这是怎么回事……

### ISSUE THREAD

**Issue by RZLNIE** [xmoeproject/KrkrExtract#2]
![image](https://cloud.githubusercontent.com/assets/17270379/13074482/bcc87a46-d4df-11e5-90b7-2b30a965632c.png)
我能理解这是后台任务正在执行中，请稍后，但我没有后台任务啊……

**Comment by xmoeproject** [comment]
咦 我看看=。=

**Comment by xmoeproject** [comment]
问题已经解决(4b版本

**Comment by RZLNIE** [comment]
多谢啦！！

2016-02-18 1:38 GMT+08:00 xmoeproject <notifications@github.com>:

> 问题已经解决(4b版本
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xmoeproject/KrkrExtract/issues/2#issuecomment-185319111>
> .
>



-- 
*动静中之动*
