### ISSUE TITLE
不支持在 steam 平台发行的版本？

### ISSUE THREAD

**Issue by KazamaSion** [xmoeproject/KrkrExtract#22]
试了一下，魔法使之夜、Nekopara 0~2 等凡是游戏使用 steam 渠道下载的版本一律都无法拆包（KrkrExtract 主界面都没弹出来）

系统：Windows 10 1703

**Comment by marcussacana** [comment]
This isn't a issue, is the CEG Protection of the steam.
You need crack the game executable to run without steam.

**Comment by KazamaSion** [comment]
@marcussacana well, thanks for answering.

**Comment by xmoeproject** [comment]
KrkrExtract 没有设计针对steam相关的破解，对于steam有各种破解或者loader加载的方式来启动游戏。KrkrExtract支持基于loader加载的Krkr引擎。
