### ISSUE TITLE
建议允许手动切换软件语言

### ISSUE THREAD

**Issue by KazamaSion** [xmoeproject/KrkrExtract#24]
krkrextract 是有中文界面的。但是我发现在更换内码为日本之后（control panel - region - administrative - language for non-Unicode language），软件语言变成了日语
![image](https://ooo.0o0.ooo/2017/06/04/5934063cde9a8.png)

有些游戏不更换内码是不能运行的。但是 krkrextract 又不允许手动切换语言。这就非常尴尬了。

**Comment by xmoeproject** [comment]
啊。。。后续的版本我已经移除中文和日语了。
反正有英文就ok了。
