### ISSUE TITLE
Nekopara vol2 support please!

### ISSUE THREAD

**Issue by leemanoid** [xmoeproject/KrkrExtract#3]
this great program worked with Nekopara vol1 and vol0 but didn't work with vol2, showing "Inner Error" dialogue.

![1456069662133](https://cloud.githubusercontent.com/assets/17384543/13203687/b29acba8-d900-11e5-8205-6baeb684ba59.jpg)

I'd appreciate if you support nekopara vol2. please!

Thanks.

**Comment by marcussacana** [comment]
Unpdated.

**Comment by leemanoid** [comment]
thanks man, newest program works fine.
