### ISSUE TITLE
Can not dump RIDDLE JOKER Xp3 Archive

### ISSUE THREAD

**Issue by jszhtian** [xmoeproject/KrkrExtract#38]
游戏：RIDDLE JOKER光盘版
KrkrExtract：4.0.0.1
dump data.xp3时出现 Fail to decompress special chunk
![default](https://user-images.githubusercontent.com/23244094/38144049-8274f214-3443-11e8-954c-afc3209cbdca.png)
疑似错误原因：
https://github.com/xmoeproject/KrkrExtract/blob/master/KrkrExtract/KrkrExtractDll/RiddleJoker_Decode.cpp
文件中RJ_ExtraDecode函数

```
mov  eax, BufSize;
push  eax;
mov eax, Output;
push eax;
mov eax, Input;
push eax;
call rj_decodep;
mov Result, eax;
```
rj_decodep中并未判断BufSize是否大于0x100
附：
![default](https://user-images.githubusercontent.com/23244094/38144206-1b66be58-3444-11e8-9e0b-fc20c741e946.png)

**Comment by xmoeproject** [comment]
忘记在这边说了，暂时不做通用提取了。按照这样做。
https://weibo.com/2670133861/G9P6H7cwY?pcfrom=msgbox&type=comment#_rnd1522425900369

后面会支持通用提取。

**Comment by xmoeproject** [comment]
本来就是cxdec，逆出这个意义也不大，不如硬断下来找call proc，然后就能用了。

**Comment by jszhtian** [comment]
cxdec是蛮讨厌的玩意。每次都追踪一轮然后硬编码确实不是个好办法。
多谢帮忙。
