### ISSUE TITLE
Riddle Joker 立绘坐标文件解密失败……？

### ISSUE THREAD

**Issue by ForsakenRei** [xmoeproject/KrkrExtract#39]
微博看到更新了正好来提个issue……

设置
PSB Package: Full upack
Text Decryption: Text
TJS2 Script: Disassembly

解包正常（除了有时解到一半就挂了）
但立绘文件夹里只有pbd文件没有前作解包后的txt立绘坐标文件……？

pbd文件头是TJS2的样子……

**Comment by CATION-M** [comment]
用GARbro的Unicode编码提取*.sinfo，再改成txt可以临时解决

**Comment by CATION-M** [comment]
看了下，*.sinfo是立绘组别信息，而根据以往的情况来看，*.pbd应该就是立绘的坐标信息

**Comment by ForsakenRei** [comment]
对，文件是找到了但看来没有解密方案……
先等等看吧

**Comment by xmoeproject** [comment]
后面会支持（现实生活太忙了）
这里面有半成品
