### ISSUE TITLE
请问目前是尚不支持对krkr Z引擎的游戏进行封包操作吗？

### ISSUE THREAD

**Issue by BSPR0002** [xmoeproject/KrkrExtract#47]
对象是krkr Z核心的“少女领域”，其他的没试过，但是只知道用打包功能封包出来的xp3文件放进游戏文件夹后进游戏会出现“Cannot convert given narrow string to wide string ”。

**Comment by xmoeproject** [comment]
1.无论是readme还是description里面都说得足够清楚了，肯定是支持的。
2.应该从你自己文本编码上做检查。
