### ISSUE TITLE
怎樣解包?

### ISSUE THREAD

**Issue by ahboy99** [xmoeproject/KrkrExtract#55]
有人知道怎樣解魔女的夜宴(原版:日本)的包嗎，我放exe在原來的exe沒出現窗口，到底有什麼問題?

**Comment by MZSHproject** [comment]
我觉得你需要读一下说明书才行。
游戏我没玩过，如果是加了壳的要先脱壳才能运行。
还有，这里是提issue的地方，不是题question的地方。
