### ISSUE TITLE
程序问题？

### ISSUE THREAD

**Issue by ztjal** [xmoeproject/KrkrExtract#56]
版本：4.0.1.1
一运行 KrkrExtract.exe ，进程自己创建了几个自己且不停关闭又启动自己
为什么发布了11 days ago了都没人报问题，还是我自己问题？WIN1803。
--------------------------------
名称: KrkrExtract.exe
大小: 145408 字节 (142 KiB)
CRC32: E842C467
--------------------------------

![捕获](https://user-images.githubusercontent.com/6552290/56854694-46b30580-696d-11e9-8023-def86a42831a.JPG)

**Comment by suzukibondo** [comment]
我的1607也是这样……不知道是咋回事……

> ## 版本：4.0.1.1
> 一运行 KrkrExtract.exe ，进程自己创建了几个自己且不停关闭又启动自己
> 为什么发布了11 days ago了都没人报问题，还是我自己问题？WIN1803。
> ## 名称: KrkrExtract.exe
> 大小: 145408 字节 (142 KiB)
> CRC32: E842C467
> ![捕获](https://user-images.githubusercontent.com/6552290/56854694-46b30580-696d-11e9-8023-def86a42831a.JPG)

**Comment by xmoeproject** [comment]
fixed, rc1 release
