### ISSUE TITLE
4.0.1.2 release版 启动问题

### ISSUE THREAD

**Issue by BSPR0002** [xmoeproject/KrkrExtract#57]
4.0.1.1 release版本 无法启动。
拖动游戏程序到krkrextract后，只有游戏主程序在运行，krkrextract的界面没有弹出，好像还有几率出现其他问题。另外杀毒软件没有像之前一样进行查杀，包括dll也没有查杀（？）。

**Comment by xmoeproject** [comment]
尝试一下4.0.1.1-rc1，如果还有问题，提供一下游戏名字。如果游戏名字过于裸露，可以发邮件提供，但是请勿在这里提供任何游戏下载链接。

**Comment by BSPR0002** [comment]
还是无法启动，无论是rc1还是rc2。还是同样的问题，进程一闪而过，只留下了游戏主程序。我甚至还把杀毒软件给关了都不行。测试环境：windows7，测试对象：（krkr2）LOVESICK PUPPIES，（krkrZ）まいてつ、NEKOPARA。目前可用的最后版本为4.0.0.5

**Comment by BSPR0002** [comment]
还是无法启动，无论是rc1还是rc2都不行，进程一闪而过，只留下了游戏主程序。
测试环境：Windows 7
测试对象：（Krkr2）LOVESICK PUPPIES，（KrkrZ）まいてつ、NEKOPARA

**Comment by xmoeproject** [comment]
你更新exe文件没

**Comment by BSPR0002** [comment]
> 你更新exe文件没

更了，两个版本的都更了一遍

**Comment by BSPR0002** [comment]
新情况，用 4.0.0.5 的exe配合 4.0.1.2 的 dll 可以正常启动，而用 4.0.1.2 的exe却不可以运行。用这种方法运行可以看到版本已经变成了 4.0.1.2 而且出现了 Virtual console 框。是不是新版的 loader 存在什么问题？还是与我的系统（Windows 7）有关？

**Comment by Mushinako** [comment]
It works when you run it in cmd/powershell (.\KrkrExtract.exe "DRIVE:\PATH\TO\GAME\EXE"). Dragging the game executable into KrkrExtract.exe does not work. Tested with exe ver 4.0.1.2 and dll ver both 4.0.1.2 and 4.0.1.3

**Comment by BSPR0002** [comment]
> It works when you run it in cmd/powershell (.\KrkrExtract.exe "DRIVE:\PATH\TO\GAME\EXE"). Dragging the game executable into KrkrExtract.exe does not work. Tested with exe ver 4.0.1.2 and dll ver both 4.0.1.2 and 4.0.1.3

Ok, thanks, although it's not convenient.
