### ISSUE TITLE
Unpack / Repack missmatch for 少女と年の差、ふたまわり。

### ISSUE THREAD

**Issue by jorgevl** [xmoeproject/KrkrExtract#60]
Hello, thank you for your great work.

I'm trying to unpack, modify and repack this game's files so I can get an english TL starting.
The .xp3 file I need to unpack/repack has .tlg and .ks files on it. I've managed to unpack it so the .ks text files appear in a readable format using the Text Decryption -> Text option, and the .tlg files are viewable using TLG Image -> Build-in Decoder option. All good.
However, when I pack the folder back to .xp3, **even if I modified nothing**, the size of the .xp3 file changes in 2bytes (for a file of 7KB~) and the game generates an error when loading this file. 

Am I missing something or is some data being lost in the packing/repacking process?
Again, thank you.

**Comment by MZSHproject** [comment]
Is the game.exe had been protected by playDRM?
About your issue,I have no idea because I never find the problem as you said.
I think you can try the universal patch.It's easy to repack.

And I think you can repack *.tlg by official tools.It will be much more stable.

**Comment by jorgevl** [comment]
> Is the game.exe had been protected by playDRM?
> About your issue,I have no idea because I never find the problem as you said.
> I think you can try the universal patch.It's easy to repack.
> 
> And I think you can repack *.tlg by official tools.It will be much more stable.

Thank you for your interest.

The .exe is not protected.
The universal patch doesn't seem to work either: I modify the .ks scenario file, run the game with the patch and my modification isn't there.
Tried unpacking/repacking everything as raw and other ways, no success.

If anyone can help, I'd really want to TL this for the english community :/
