### ISSUE TITLE
Un/Repack Error:かりぐらし恋愛（krkrZ）

### ISSUE THREAD

**Issue by MZSHproject** [xmoeproject/KrkrExtract#61]
游戏原版的tpm带Anti-Inject，导致程序注入后无法进行解包操作。不过可以使用体验版程序进行解包。
在封包的时候把所有修改过的文件放在一个文件夹内然后进行封包，出现无法打开文件的情况。
以及在使用通用补丁时会有一部分文件无法读取（未更改文件名）。

目前我的解决办法就是找一个krkr2的程序然后进行封包，忽视弹出来的错误。不过这种做法始终是临时救急用。如果大大有时间的话还请看一下这个游戏的问题。谢谢

**Comment by xmoeproject** [comment]
关于只有一部分文件才能读取出来的问题，其实我很久之前已经有解决方案了，只是还没写进去。有空我我加进去。

**Comment by MZSHproject** [comment]
好的，感谢大佬。

**Comment by xmoeproject** [comment]
新版的Universal patch已经能重载startup.tjs了
