### ISSUE TITLE
柚子新作喫茶ステラと死神の蝶文本提取失败

### ISSUE THREAD

**Issue by greenjerry** [xmoeproject/KrkrExtract#73]
柚子新作喫茶ステラと死神の蝶文本提取失败，其余功能正常
初步断定原因出自：
旧版.scn文件转换成json后人名和所说的话之间只有"null,"，而新版变成了"[\n[\nnull,"多加了两行"["和"]"和一个奇怪的数字，以至于提取出的txt只有人名而无其他文字

目前暂确认decompiled的tlg和json文件无误，可以写脚本从tlg或json中提取全部文本成功，封包能否成功暂未测试

麻烦更新并处理一下这个小问题，谢谢！

**Comment by xmoeproject** [comment]
问题类似#72 
本来厂商就可以随意设置文本的tag，所以没有什么通用的好方法。
开源就为了大家一起建设，你完全可以把你在脚本开一个PR然后我merge到toolchain之类的文件夹中

**Comment by jszhtian** [comment]
一般都是解psb到json，然后自己跑脚本来替换文本。每个厂商的json配置都有少许不同，想搞统一的程序有点麻烦，除非在解包的时候能设置json的tag信息。


[Script_tools.zip](https://github.com/xmoeproject/KrkrExtract/files/3994617/Script_tools.zip)
