### ISSUE TITLE
Can't unpack SenrenBanka's XP3

### ISSUE THREAD

**Issue by hlgsdx** [xmoeproject/KrkrExtract#8]
Screenshoot here: http://i4.piimg.com/1949/06e6a355ad90faf4.png
It seems that yozusoft has updated their pack method........

**Comment by games1tw** [comment]
千恋＊万花体验版能拆，可惜正式版我也跟楼主的图一样拆不开

**Comment by erowalker** [comment]
同样的问题，正式版不管拆哪个包都会inner error

**Comment by xmoeproject** [comment]
Version 1.0.2.0 solved this issue.
只做了一点微小的工作 很惭愧
