### ISSUE TITLE
封包的问题

### ISSUE THREAD

**Issue by Enanaya** [xmoeproject/KrkrExtract#90]
xmeo老师，我在翻译一个kirikiri的游戏，该游戏打了patch_1的补丁。我在拆包patch_1和data.xp3翻译完后不封包直接运行游戏无法读取补丁只有原本data的内容（也就是dlc没有打上）。使用krkrExtract封包时提示couldn't open krmovie.dll
![QQ截图20200904182800](https://user-images.githubusercontent.com/24999161/92229674-6997e700-eedc-11ea-8948-e07fe3651bdb.png)

**Comment by Enanaya** [comment]
Folder里是已经拆包翻译好的资源，original pack里是没有拆包原资源文件

**Comment by Enanaya** [comment]
大概已经通过其他软件解决了。非常感谢！

**Comment by xmoeproject** [comment]
建议使用Universal patch功能，v5完全重写了，应该逻辑上不会有这么多的问题。

**Comment by Enanaya** [comment]
> 建议使用Universal patch功能，v5完全重写了，应该逻辑上不会有这么多的问题。

可能因为是kirikiri1，universal patch会提示无法分析游戏，但已经通过GARbor解决封包问题，非常感谢回答！
