### ISSUE TITLE
アインシュタインより愛を込めて

### ISSUE THREAD

**Issue by rinnow** [xmoeproject/KrkrExtract#92]
I tried to extract アインシュタインより愛を込めて but it doesn't work for the trial version.
I really do appriciate it if you correspond for this game.

https://glovety.product.co.jp/#top
you can get the trial version from here just in case.

**Comment by MishaIac** [comment]
![image](https://user-images.githubusercontent.com/47920105/93014898-865bab00-f5bd-11ea-80d3-8ce33def6859.png)

**Comment by rinnow** [comment]
I missed it. Should have posted it to siglus extract.
