### ISSUE TITLE
关于v5-preview分支的编译问题

### ISSUE THREAD

**Issue by AyamiKaze** [xmoeproject/KrkrExtract#93]
xmoe大大好。最近我在自己尝试编译v5-preview时遇到了问题，编译时遇到了许多Native无法编译，导致其他的项目编译失败。我的编译环境是VS2019，请问这个该如何配置或者解决，谢谢。
![R6V~7250FD02L$ZR`VFKH48](https://user-images.githubusercontent.com/47900658/93550449-fdb68380-f99d-11ea-8cd2-6d01f13d557a.png)

**Comment by xmoeproject** [comment]
1.NativeLib项目暂时不支持vs2019 toolchain的编译，后续某一天可能会解决，或者请在vs2019中安装vs2017版本的msvc
2.v5分支（包括当前master分支头几个提交）都不要使用，后续可能会有很多修修改改

**Comment by AyamiKaze** [comment]
> 1.NativeLib项目暂时不支持vs2019 toolchain的编译，后续某一天可能会解决，或者请在vs2019中安装vs2017版本的msvc
> 2.v5分支（包括当前master分支头几个提交）都不要使用，后续可能会有很多修修改改

好的，感谢解答。
