### ISSUE TITLE
Systeminfo dll Error

### ISSUE THREAD

**Issue by JHPY** [xmoeproject/KrkrExtract#96]
![image](https://user-images.githubusercontent.com/71465644/94460493-63e7a580-01eb-11eb-89d0-f2c0c956011d.png)

Hello, I am getting this error when I try to open Bishoujo Mangekyou 5 with Krkrextract. Can someone help? All the Krkrextract files are at the game folder. The game folder is in Program Files x86.

**Comment by MishaIac** [comment]
![image](https://user-images.githubusercontent.com/47920105/97878196-fa494280-1d26-11eb-9c5b-2cd896568ec1.png)

**Comment by JHPY** [comment]
Thanks, I managed to find the script files manually without using an extractor.
